const widgetsComponentsTypes = {

	button: WidgetButton,
	label: WidgetLabel,
	input: WidgetInput,
	textArea: WidgetTextArea,
	smartImage: WidgetSmartImage,
	table: WidgetTable,
	window: WidgetWindow,
	layout: WidgetLayout,
	layoutVertical: WidgetLayoutVertical,
	layoutHorizontal: WidgetLayoutHorizontal,
	layoutGrid: WidgetLayoutGrid,
	layoutFlex: WidgetLayoutFlex,
	tab: WidgetTab,
	sideBars: WidgetSideBars,
	messagesViewer: WidgetMessagesViewer,
	contacts: WidgetContacts,
	loading: WidgetLoading,
	dialog: WidgetDialog,
	comboBox: WidgetComboBox,
	calendar: WidgetCalendar,
	tree: WidgetTree,
	treeItem: WidgetTreeItem,
	spinBox: WidgetSpinBox,
	checkBox: WidgetCheckBox,
	geoMap: WidgetGeoMap,
	Frame: WidgetFrame,
	CompareT: CompareTable
}